# Generated by Django 3.2.9 on 2022-01-11 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_posts_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsAndTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
                ('tagID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.tags')),
            ],
        ),
    ]
