# Generated by Django 3.2.9 on 2022-01-12 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_postsandtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsandtags',
            name='postID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.posts'),
        ),
        migrations.AlterField(
            model_name='postsandtags',
            name='tagID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.tags'),
        ),
    ]
