# Generated by Django 3.2.9 on 2022-01-12 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220112_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsandtags',
            name='postID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.posts'),
        ),
        migrations.AlterField(
            model_name='postsandtags',
            name='tagID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.tags'),
        ),
    ]
