# Generated by Django 3.2.9 on 2022-01-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220112_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='content',
        ),
        migrations.AddField(
            model_name='tags',
            name='tagContent',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
