# Generated by Django 3.2.9 on 2022-01-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20220119_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentsThumbs',
        ),
    ]
