# Generated by Django 3.2.9 on 2022-01-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('posts', '0015_delete_commentsthumbs'),
        ('accounts', '0006_alter_customuser_profilepicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
